package es.upm.dit.gsi.trainmining;

import es.upm.dit.gsi.trainmining.model.Alarm;
import es.upm.dit.gsi.trainmining.model.PossibleEvent;
global java.util.List resultList;

rule "rule0"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.90311625);
        resultList.add(p);
end

rule "rule1"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.90311625);
        resultList.add(p);
end

rule "rule2"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.90281383);
        resultList.add(p);
end

rule "rule3"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.90281383);
        resultList.add(p);
end

rule "rule4"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.89899642);
        resultList.add(p);
end

rule "rule5"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.898694);
        resultList.add(p);
end

rule "rule6"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.89588915);
        resultList.add(p);
end

rule "rule7"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.89549203);
        resultList.add(p);
end

rule "rule8"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.89158789);
        resultList.add(p);
end

rule "rule9"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.89158789);
        resultList.add(p);
end

rule "rule10"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.89118466);
        resultList.add(p);
end

rule "rule11"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.89118466);
        resultList.add(p);
end

rule "rule12"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.88508279);
        resultList.add(p);
end

rule "rule13"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.88467956);
        resultList.add(p);
end

rule "rule14"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.88316599);
        resultList.add(p);
end

rule "rule15"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.88235852);
        resultList.add(p);
end

rule "rule16"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.88197552);
        resultList.add(p);
end

rule "rule17"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.88181739);
        resultList.add(p);
end

rule "rule18"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.88147759);
        resultList.add(p);
end

rule "rule19"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.88105827);
        resultList.add(p);
end

rule "rule20"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.87425175);
        resultList.add(p);
end

rule "rule21"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.87156308);
        resultList.add(p);
end

rule "rule22"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.86792392);
        resultList.add(p);
end

rule "rule23"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_DIS_chann0_DO_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.86511942);
        resultList.add(p);
end

rule "rule24"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.8001828);
        resultList.add(p);
end

rule "rule25"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.79523375);
        resultList.add(p);
end

rule "rule26"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO","environmentAlarm",iid,0.78961581);
        resultList.add(p);
end

rule "rule27"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.78902397);
        resultList.add(p);
end

rule "rule28"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP");
        Alarm(installationID == iid, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.78055866);
        resultList.add(p);
end

rule "rule29"
    when 
        Alarm(iid : installationID, alarmCode == "clc.NCEC_OCS_state_CON_chann0_UP_chann1_DO");
    then 
        PossibleEvent p = new PossibleEvent("clc.NCEC_OCS_state_CON_chann0_DO_chann1_UP","environmentAlarm",iid,0.76943982);
        resultList.add(p);
end

